// export const DEMO = 'DEMO'
export const GET_ITEMS = 'GET_ITEMS'
export const CUT_TAB = 'CUT_TAB'
export const TABS_CUT = 'TABS_CUT'
export const ADD_TAB = 'ADD_TAB'
export const REMOVE_TAB = 'REMOVE_TAB'
